---
destination: /home/user #Это путь к каталогу на целевой машине, куда нужно установить
elk_version: 7.17.14 #Это версия Elastic Stack
elk_source:  /home/kvv/distrib/ #Это путь к каталогу или файлу, где находятся установочные файлы 
