---
- name: Install elasticsearch # Установка elasticsearch на elastic_server
  hosts: elasticsearch_host
  become: yes

  vars_files: ./elk/vars.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install gnupg, apt-transport-https # Установка необходимых пакетов
      apt:
        name:
          - apt-transport-https
          - gnupg
        state: present

    - name: Copy elasticsearch deb package # Копирование деб пакета на сервер elasticsearch
      copy:
        src: "{{ elk_source }}/elasticsearch-{{ elk_version }}-amd64.deb"
        dest: "{{ destination }}"

    - name: Install elasticsearch # Установка elasticsearch
      apt:
        deb: "{{ destination }}/elasticsearch-{{ elk_version }}-amd64.deb"
      notify: 
        - restart elasticsearch

    - name: Copy config file for elasticsearch # Копирование конфига на сервер elasticsearch
      copy:
        src: ./elk/elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml
        mode: '0660'
        owner: root
        group: elasticsearch
      notify:
        - restart elasticsearch

  handlers:
    - name: restart elasticsearch
      systemd:
        daemon_reload: yes
        name: elasticsearch.service
        state: restarted
        enabled: yes
